### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by GoCross** [Inv0k3r/DOTA2_Bot#11]
今天(20.11.25)更新了一哈，然后`python3 run.py`报错
```
Traceback (most recent call last):
  File "run.py", line 70, in <module>
    main()
  File "run.py", line 60, in main
    if init() != -1:
  File "run.py", line 29, in init
    if not is_player_stored(short_steamID):
  File "/home/zhao/project/dota2_bot/DBOper.py", line 34, in is_player_stored
    c.execute("SELECT * FROM playerInfo WHERE short_steamID=={}".format(short_steamID))
sqlite3.OperationalError: no such table: playerInfo
```

**Comment by Lucifer-ly** [comment]
DBOper.py里面的数据库的位置改一下
